<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\OrderController;

// Public route for the welcome page
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// IMPORTANT: Include Laravel Breeze's authentication routes
// These are generated by `php artisan breeze:install` and stored in routes/auth.php
require __DIR__.'/auth.php';

// Admin routes, protected by 'auth' middleware
Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'index'])->name('dashboard');

    // Resource routes for packages
    Route::resource('packages', PackageController::class);

    // Orders routes
    Route::get('/orders', [OrderController::class, 'index'])->name('orders.index');
});

// Logout route (This is already handled by Breeze's routes, but keeping it explicit is fine)
Route::post('/logout', function () {
    Auth::logout();
    request()->session()->invalidate();
    request()->session()->regenerateToken();
    return redirect('/login');
})->name('logout');